export const ADD_TO_CART = "ADD_TO_CART"
export const DEC_FROM_CART = "DEC_FROM_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const LOG_OUT = "LOG_OUT"
export const LOG_IN = "LOG_IN"